# Generated by Django 4.2.3 on 2024-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
